<?php

declare(strict_types=1);

use ApexDocs\ApexDocs;
use ApexDocs\Config;
use ApexDocs\Http\Handler;
use ApexDocs\Http\UiRenderer;
use ApexDocs\Route\ArrayRouteCollection;
use Nyholm\Psr7\Factory\Psr17Factory;

/**
 * End-to-end PSR-15 path. Builds the Handler with real PSR-17 factories
 * (nyholm/psr7) and exercises every route the package exposes. If any of
 * these fail, PSR-15 users (Slim, Mezzio, raw middleware stacks) can't
 * serve the documentation.
 */
function buildHandler(): Handler
{
    $psr17 = new Psr17Factory;
    $apex = ApexDocs::make(new Config(
        title: 'PSR-15 API',
        version: '1.0.0',
        servers: [['url' => 'http://localhost']],
    ))->routes(new ArrayRouteCollection);

    return new Handler($apex, $psr17, $psr17, new UiRenderer);
}

function psrRequest(string $path): \Psr\Http\Message\ServerRequestInterface
{
    return (new Psr17Factory)->createServerRequest('GET', 'http://localhost'.$path);
}

it('returns JSON for /spec.json', function () {
    $resp = buildHandler()->handle(psrRequest('/docs/spec.json'));

    expect($resp->getStatusCode())->toBe(200)
        ->and($resp->getHeaderLine('Content-Type'))->toBe('application/json')
        ->and($resp->getHeaderLine('Access-Control-Allow-Origin'))->toBe('*')
        ->and($resp->getHeaderLine('Cache-Control'))->toBe('no-store');

    $body = (string) $resp->getBody();
    expect(json_decode($body, true))->toBeArray();
});

it('returns YAML for /spec.yaml', function () {
    $resp = buildHandler()->handle(psrRequest('/docs/spec.yaml'));

    expect($resp->getStatusCode())->toBe(200)
        ->and($resp->getHeaderLine('Content-Type'))->toBe('application/yaml')
        ->and((string) $resp->getBody())->toContain('openapi: 3.1.0');
});

it('attaches a Content-Disposition for Postman, Insomnia, and Bruno downloads', function (string $route, string $filename) {
    $resp = buildHandler()->handle(psrRequest($route));

    expect($resp->getStatusCode())->toBe(200)
        ->and($resp->getHeaderLine('Content-Disposition'))->toContain($filename)
        ->and($resp->getHeaderLine('Content-Type'))->toBe('application/json');
})->with([
    ['/docs/postman', 'postman-collection.json'],
    ['/docs/insomnia', 'insomnia-collection.json'],
    ['/docs/bruno', 'bruno-collection.json'],
]);

it('serves the UI HTML at the docs root', function () {
    $resp = buildHandler()->handle(psrRequest('/docs'));

    expect($resp->getStatusCode())->toBe(200)
        ->and($resp->getHeaderLine('Content-Type'))->toStartWith('text/html');

    $html = (string) $resp->getBody();
    expect($html)->toContain('<html')->toContain('</html>');
});

it('uses the same JSON bytes that the Laravel route would (parity check)', function () {
    // The HTTP path and DocsController both flow through SpecPayload, so the
    // generated bytes for /spec.json must be identical here as in the Laravel
    // suite. This test catches drift if anyone forks the response wiring.
    $resp = buildHandler()->handle(psrRequest('/docs/spec.json'));
    $body = (string) $resp->getBody();

    expect(json_decode($body, true))
        ->toHaveKey('openapi')
        ->toHaveKey('info');
});
